Repository mju-ai-pro/ai-pro-server, pull requests merged in 2024-12, with the labels that each got.

#67 fix: fixed AiRequest format
  src/main/java/teamproject/aipro/domain/chat/dto/request/AiRequest.java
  src/main/java/teamproject/aipro/domain/chat/service/ChatHistoryService.java
  src/main/java/teamproject/aipro/domain/chat/service/ChatService.java
Labels: 🚨긴급

#69 Refactor/chat
  bin/main/application.yml
  src/main/java/teamproject/aipro/domain/chat/controller/ChatController.java
  src/main/java/teamproject/aipro/domain/chat/service/ChatHistoryService.java
  src/main/java/teamproject/aipro/domain/chat/service/ChatService.java
Labels: 🎯리팩토링

#70 chore: jacoco 적용
  .github/workflows/sonar-cloud.yml
  build.gradle
Labels: 🌍인프라

#74 Refactor/chat
  src/main/java/teamproject/aipro/domain/chat/controller/ChatController.java
  src/test/java/teamproject/aipro/domain/chat/ChatControllerTest.java
  src/test/java/teamproject/aipro/domain/chat/ChatServiceTest.java
Labels: 🎯리팩토링

#76 Fix/chat
  src/main/java/teamproject/aipro/config/SecurityConfig.java
  src/main/java/teamproject/aipro/config/WebConfig.java
Labels: 🚨긴급

#81 fix: allowed all origin patterns.
  src/main/java/teamproject/aipro/config/SecurityConfig.java
Labels: 🚨긴급

#82 fix: restored RestTemplate injection.
  src/main/java/teamproject/aipro/config/WebConfig.java
Labels: 🚨긴급

#83 fix: added duplication remover in MemberService.
  src/main/java/teamproject/aipro/domain/member/controller/MemberController.java
  src/main/java/teamproject/aipro/domain/member/repository/MemberRepository.java
  src/main/java/teamproject/aipro/domain/member/service/MemberService.java
Labels: 🚨긴급

#95 fix: added logger.
  src/main/resources/application.yml
Labels: 🛠️버그
