Repository mju-ai-pro/ai-pro-server, pull requests merged in 2024-11, with the labels that each got.

#38 Fix/cors
  src/main/java/teamproject/aipro/config/SecurityConfig.java
Labels: 🚨긴급

#44 Feat/member
  src/main/java/teamproject/aipro/config/SecurityConfig.java
  src/main/java/teamproject/aipro/config/jwt/JwtAuthenticationFilter.java
  src/main/java/teamproject/aipro/domain/member/controller/MemberController.java
  src/main/java/teamproject/aipro/domain/member/dto/request/LoginRequest.java
  src/main/java/teamproject/aipro/domain/member/dto/request/SignupRequest.java
  src/main/java/teamproject/aipro/domain/member/dto/response/MemberResponse.java
  src/main/java/teamproject/aipro/domain/member/entity/Member.java
  src/main/java/teamproject/aipro/domain/member/repository/MemberRepository.java
  src/main/java/teamproject/aipro/domain/member/service/MemberService.java
  src/main/resources/application.yml
Labels: ✨기능

#47 Origin/feat/chatHistory
  src/main/java/teamproject/aipro/domain/chat/controller/ChatHistoryController.java
  src/main/java/teamproject/aipro/domain/chat/service/ChatService.java
Labels: ✨기능

#53 fix/login
  src/main/java/teamproject/aipro/domain/member/controller/MemberController.java
Labels: ✨기능

#55 Fix/login
  src/main/java/teamproject/aipro/domain/member/controller/MemberController.java
Labels: ✨기능

#59 Fix/access token
  src/main/java/teamproject/aipro/config/jwt/JwtAuthenticationFilter.java
Labels: ✨기능

#61 refactor: role자료구조 변경 및 Principal 추가
  src/main/java/teamproject/aipro/domain/chat/service/ChatService.java
  src/main/java/teamproject/aipro/domain/role/controller/RoleController.java
  src/main/java/teamproject/aipro/domain/role/dto/request/RoleRequest.java
  src/main/java/teamproject/aipro/domain/role/service/RoleService.java
Labels: 🎯리팩토링
